const data = {
    products: [
      {
        _id: '1',
        name: 'Midnight Pin Dot Tuxedo',
        category: 'Suits & Tuxedos',
        image: '/images/p1.jpg',
        price: 1200,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.9,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'BLUE DRESS SHIRT',
        category: 'Shirts',
        image: '/images/p2.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'BLUE SUIT VEST',
        category: 'VESTs',
        image: '/images/p3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'COTTON FLY-FRONT DRESS SHIRT',
        category: 'Shirts',
        image: '/images/p4.jpg',
        price: 190,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Black Satin Necktie',
        category: 'Neckwear',
        image: '/images/p5.jpg',
        price: 250,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Black Patent Leather Shoes',
        category: 'Shoes',
        image: '/images/p6.jpg',
        price: 150,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;